#!/bin/bash
# Comet CodeGraph context exporter — build an index and write a compact scan context.
# Usage: comet-codegraph-context.sh [project-path] [output-file]

set -euo pipefail

red() { echo -e "\033[31m$1\033[0m" >&2; }
green() { echo -e "\033[32m$1\033[0m" >&2; }
yellow() { echo -e "\033[33m$1\033[0m" >&2; }

PROJECT_PATH="${1:-.}"
OUTPUT_FILE="${2:-openspec/.comet/codegraph-context.md}"

if ! command -v codegraph >/dev/null 2>&1; then
  red "ERROR: codegraph command not found"
  red "Install CodeGraph CLI, then rerun /comet-scan."
  exit 127
fi

PROJECT_PATH="$(cd "$PROJECT_PATH" && pwd -P)"
cd "$PROJECT_PATH"

mkdir -p "$(dirname "$OUTPUT_FILE")"
SYMBOLS_FILE="$(mktemp)"
REFS_FILE="$(mktemp)"
trap 'rm -f "$SYMBOLS_FILE" "$REFS_FILE"' EXIT

strip_ansi() {
  sed -E $'s/\x1B\\[[0-9;]*[[:alpha:]]//g'
}

collect_symbols_from_file() {
  local file="$1"
  awk '
    /^(function|method|class|constant|interface|type)[[:space:]]+/ {
      print $2
    }
  ' "$file" >> "$SYMBOLS_FILE"
}

collect_refs_from_file() {
  local file="$1"
  awk '
    /^[[:space:]]+[^[:space:]]+:[0-9]+/ {
      ref = $1
      sub(/^[[:space:]]+/, "", ref)
      n = split(ref, parts, ":")
      line = parts[n]
      path = substr(ref, 1, length(ref) - length(line) - 1)
      if (path != "" && line ~ /^[0-9]+$/) {
        print path ":" line
      }
    }
  ' "$file" >> "$REFS_FILE"
}

append_command_section() {
  local title="$1"
  shift
  local tmp_file
  tmp_file="$(mktemp)"

  {
    echo ""
    echo "## $title"
    echo ""
    echo '```text'
  } >> "$OUTPUT_FILE"

  if "$@" 2>&1 | strip_ansi > "$tmp_file"; then
    cat "$tmp_file" >> "$OUTPUT_FILE"
    collect_symbols_from_file "$tmp_file"
    collect_refs_from_file "$tmp_file"
    :
  else
    local status=$?
    cat "$tmp_file" >> "$OUTPUT_FILE"
    collect_symbols_from_file "$tmp_file"
    collect_refs_from_file "$tmp_file"
    echo "[command failed: $*] exit=$status" >> "$OUTPUT_FILE"
  fi

  echo '```' >> "$OUTPUT_FILE"
  rm -f "$tmp_file"
}

append_query_section() {
  local term="$1"
  local tmp_file
  tmp_file="$(mktemp)"

  {
    echo ""
    echo "## Symbol Search: $term"
    echo ""
    echo '```text'
  } >> "$OUTPUT_FILE"

  if codegraph query "$term" 2>&1 | strip_ansi > "$tmp_file"; then
    cat "$tmp_file" >> "$OUTPUT_FILE"
    collect_symbols_from_file "$tmp_file"
    collect_refs_from_file "$tmp_file"
  else
    local status=$?
    cat "$tmp_file" >> "$OUTPUT_FILE"
    collect_symbols_from_file "$tmp_file"
    collect_refs_from_file "$tmp_file"
    echo "[command failed: codegraph query $term] exit=$status" >> "$OUTPUT_FILE"
  fi

  echo '```' >> "$OUTPUT_FILE"
  rm -f "$tmp_file"
}

append_relation_sections() {
  {
    echo ""
    echo "## Relationship Analysis"
    echo ""
    echo "The sections below are generated from CodeGraph callers/callees/impact commands. Use them to attribute behavior to the correct caller instead of guessing from file names alone."
  } >> "$OUTPUT_FILE"

  {
    cat "$SYMBOLS_FILE" 2>/dev/null || true
    printf '%s\n' \
      summarizeDashboard summarizeProject createRouter route createMemoryStore \
      listProjects listTasks addTask createTask isOpenTask sendJson sendNotFound
  } | awk 'NF && !seen[$0]++' | head -n 40 | while IFS= read -r symbol; do
    append_command_section "Callees: $symbol" codegraph callees "$symbol"
    append_command_section "Callers: $symbol" codegraph callers "$symbol"
    append_command_section "Impact: $symbol" codegraph impact "$symbol"
  done
}

append_targeted_source_excerpts() {
  {
    echo ""
    echo "## Targeted Source Excerpts"
    echo ""
    echo "These snippets are selected from CodeGraph-reported file:line references. Use them only to resolve behavior that relationship commands cannot fully express; this is not a full repository scan."
  } >> "$OUTPUT_FILE"

  awk 'NF && !seen[$0]++' "$REFS_FILE" | head -n 60 | while IFS= read -r ref; do
    local file="${ref%:*}"
    local line="${ref##*:}"

    if [ ! -f "$file" ]; then
      continue
    fi

    local start end
    start=$((line - 8))
    if [ "$start" -lt 1 ]; then
      start=1
    fi
    end=$((line + 12))

    {
      echo ""
      echo "### $file:$line"
      echo ""
      echo '```text'
      awk -v start="$start" -v end="$end" 'NR >= start && NR <= end { printf "%6d  %s\n", NR, $0 }' "$file"
      echo '```'
    } >> "$OUTPUT_FILE"
  done
}

cat > "$OUTPUT_FILE" <<EOF
# CodeGraph Scan Context

Generated by Comet from CodeGraph CLI output.

- Project: $PROJECT_PATH
- Index DB: $PROJECT_PATH/.codegraph/codegraph.db
- Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

Use this file as the primary input for OpenSpec exploration. Read source files only when this context points to them or when a specific behavior is still ambiguous.
EOF

append_command_section "Index Output" codegraph index "$PROJECT_PATH"
append_command_section "Index Status" codegraph status "$PROJECT_PATH"
append_command_section "Indexed File Structure" codegraph files

for term in server route router controller handler service store storage model domain task test spec config summary index; do
  append_query_section "$term"
done

append_relation_sections
append_targeted_source_excerpts

green "CodeGraph context written: $OUTPUT_FILE"
